export enum VariantEnum {
  'accent' = 'accent',
  'accent-1' = 'accent-1',
  'accent-2' = 'accent-2',
  'primary' = 'primary',
  'primary-1' = 'primary-1',
  'primary-2' = 'primary-2',
  'secondary' = 'secondary',
  'secondary-1' = 'secondary-1',
  'secondary-2' = 'secondary-2',
  'negative' = 'negative',
  'negative-1' = 'negative-1',
  'negative-2' = 'negative-2',
  'dark' = 'dark',
  'dark-1' = 'dark-1',
  'dark-2' = 'dark-2',
  'light' = 'light',
  'light-1' = 'light-1',
  'light-2' = 'light-2',
}
