export enum VariantEnum {
  ACCENT = 'accent',
  ACCENT1 = 'accent-1',
  ACCENT2 = 'accent-2',
  PRIMARY = 'primary',
  PRIMARY1 = 'primary-1',
  PRIMARY2 = 'primary-2',
  SECONDARY = 'secondary',
  SECONDARY1 = 'secondary-1',
  SECONDARY2 = 'secondary-2',
  NEGATIVE = 'negative',
  NEGATIVE1 = 'negative-1',
  NEGATIVE2 = 'negative-2',
  DARK = 'dark',
  DARK1 = 'dark-1',
  DARK2 = 'dark-2',
  LIGHT = 'light',
  LIGHT1 = 'light-1',
  LIGHT2 = 'light-2',
}
